# Separate deploy-prod job for manual trigger
name: Deploy to Production

env:
  AZURE_WEBAPP_NAME_PROD: quartile-app-prod

on:
  workflow_dispatch:

permissions:
  contents: none
  packages: write

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp-prod.outputs.webapp-url }}

    steps:
      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Deploy to Azure Web App (Production)
        id: deploy-to-webapp-prod
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME_PROD }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          images: 'ghcr.io/${{ env.REPO }}:${{ github.sha }}'
